### ISSUE TITLE
I hope to add 2 functions, 1. timeout to re-release the fishing rod; 2. fishing rod release speed adjustment

### ISSUE THREAD

**Issue by Mrbluewu** [Tr4nter/Auto-Fishing#1]
I hope to add 2 functions, 1. timeout to re-release the fishing rod; 2. fishing rod release speed adjustment

**Comment by Tr4nter** [comment]
https://modrinth.com/mod/auto-fishing/version/1.0.1
I added 2 new commands:
/RodCatchDelay and /RodReleaseDelay
