### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by DaSB101** [Tr4nter/Auto-Fishing#5]
It worked, but then My fishing rod broke, so I switched, and then it stopped working.

**Comment by DaSB101** [comment]
i had to completely exit Minecraft for it to work

**Comment by Tr4nter** [comment]
I tried to reproduce the problem and for me it worked, what was the minecraft version + mod version that the bug happened?

**Comment by ExaminedBiscuit** [comment]
@Tr4nter I run into the same issue. Once a rod breaks, the new rod will not auto-catch and I have to completely exit out of Minecraft. I am using Fabric 1.21. Auto fishing is  v1.0.2

**Comment by Tr4nter** [comment]
> @Tr4nter I run into the same issue. Once a rod breaks, the new rod will not auto-catch and I have to completely exit out of Minecraft. I am using Fabric 1.21. Auto fishing is v1.0.2

Hello, I have tried to reproduce the problem both on 1.20.6, 1.21 on both singleplayer and multiplayer without any success, however i have made changes that I assume may be able to ease off the possibilities of this happening, please try out the new version and let me know
https://modrinth.com/mod/auto-fishing/version/3RVloFN1

**Comment by ExaminedBiscuit** [comment]
> Hello, I have tried to reproduce the problem both on 1.20.6, 1.21 on both singleplayer and multiplayer without any success, however i have made changes that I assume may be able to ease off the possibilities of this happening, please try out the new version and let me know https://modrinth.com/mod/auto-fishing/version/3RVloFN1

Just tested using an almost-used fishing rod and was able to switch to a new one after it broke. I can keep fishing. Thank you!
