### ISSUE TITLE
No enchantments?

### ISSUE THREAD

**Issue by Zeuqalpad** [Tr4nter/Auto-Fishing#6]
I believe I used auto fishing 100+ times and still no enchantments at all. My release is 700. Catch is 400.

**Comment by Tr4nter** [comment]
https://minecraft.wiki/w/Fishing
```To catch items in the treasure category, the bobber must be in open water, defined as the 5×4×5 vicinity around the bobber resting on the water surface (2 blocks away horizontally, 2 blocks above the water surface, and 2 blocks deep). Each horizontal layer in this area must consist only of [air](https://minecraft.wiki/w/Air) and [lily pads](https://minecraft.wiki/w/Lily_pad) or [water](https://minecraft.wiki/w/Water) source blocks, [waterlogged](https://minecraft.wiki/w/Waterlogged) blocks without collision (such as signs, kelp, or coral fans), and [bubble columns](https://minecraft.wiki/w/Bubble_column). These conditions are checked every [tick](https://minecraft.wiki/w/Tick) to determine if the player is eligible to receive treasure from a fishing attempt. If the conditions are not met, only items in the fish and junk categories can be obtained from fishing.```
