### ISSUE TITLE
[Feature/Bug] Secondary hand fishing

### ISSUE THREAD

**Issue by tonitch** [Tr4nter/Auto-Fishing#7]
sometimes I get attacked while fishing. I then put my fishing rod on my second hand to use my sword to kill the monster.
the mod doesn't seem to work with the secondary hand. I don't really know if this is a bug or if this is indended tho ^^ 

Aside from that, the mod is simple and great ^^ I had to ajust timing because the rod was fishing the item coming toward me but everything is fine now

**Comment by Tr4nter** [comment]
Thanks for your suggestion, I have added off-hand support.

https://modrinth.com/mod/auto-fishing/version/3RVloFN1
